/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
import static javafx.application.Application.launch;

public class App {
    public static void main(String[] args) {
        launch(Game.class);
    }
}
